### ISSUE TITLE
Allow user to select a title column

### ISSUE THREAD

**Issue by jamesmunns** [Aaronepower/csv-to-md#1]
It would be nice to allow the user to specify a "title column", where the contents of that row would be an `h1`, and the column title would be omitted. This could default to the first column

This would generate something like the following

```csv
name, favorite number, favorite food
alice, 7, nachos
bob, 12, pizza
```

```markdown
# alice

##### favorite number

7

##### favorite food

nachos

# bob

##### favorite number

12

##### favorite food

pizza
```

Submitting an issue because I thought it would be useful. I may implement at a later date if you haven't already :)

Thanks for the cool tool!

**Comment by XAMPPRocky** [comment]
Thank you for your issue this has now been added in the form of `-t/--title`.
